add: tini, restic, terraform & packer

diff --git a/scripts/modules/docker/downloadGosu b/scripts/modules/docker/downloadGosu
--- a/scripts/modules/docker/downloadGosu
+++ b/scripts/modules/docker/downloadGosu
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 # @import console/die
-# @import hashicorp/hashicorpKey
 # @import lang/exists
 # @import stack-tools/stackToolsDefaults
 
@@ -11,21 +10,22 @@ downloadGosu ()
 
     exists gpg || die "Cannot find 'gpg' in path."
     exists curl || die "Cannot find 'gpg' in path."
-    exists unzip || die "Cannot find 'unzip' in path."
 
     stackToolsDefaults
 
     {
-        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
+        gpg --batch --keyserver ha.pool.sks-keyservers.net \
+            --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 &> /dev/null
     } || die "Cannot import tianon GPG key"
 
     [ -z "${GOSU_BINARY}" ] && die "'GOSU_BINARY' is not defined"
+    [ -z "${GOSU_BINARY_SIGNATURE}" ] && die "'GOSU_BINARY_SIGNATURE' is not defined"
     [ -z "${GOSU_SHA256SUMS}" ] && die "'GOSU_SHA256SUMS' is not defined"
     [ -z "${GOSU_SHA256SUMS_SIGNATURE}" ] && die "'GOSU_SHA256SUMS_SIGNATURE' is not defined"
 
     [ -z "${GOSU_DIRECTORY}" ] && GOSU_DIRECTORY="${MANAGE_REPOSITORY}/vendor/gosu"
 
-    if [ ! -f "${GOSU_DIRECTORY}/packer" ]
+    if [ ! -f "${GOSU_DIRECTORY}/gosu" ]
     then
         mkdir -p "${GOSU_DIRECTORY}"
         curl -0 -S -L --progress-bar "${GOSU_BINARY}" -o "${GOSU_DIRECTORY}/${GOSU_BINARY##*/}"
@@ -33,11 +33,15 @@ downloadGosu ()
         curl -0 -s -S -L "${GOSU_SHA256SUMS}" -o "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}"
         curl -0 -s -S -L "${GOSU_SHA256SUMS_SIGNATURE}" -o "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS_SIGNATURE##*/}"
 
-        gpg --batch --verify "${GOSU_DIRECTORY}/${GOSU_BINARY_SIGNATURE##*/}" \
-            "${GOSU_DIRECTORY}/${GOSU_BINARY##*/}"
+        {
+            gpg --batch --verify "${GOSU_DIRECTORY}/${GOSU_BINARY_SIGNATURE##*/}" \
+                "${GOSU_DIRECTORY}/${GOSU_BINARY##*/}" &> /dev/null
+        } || die "Cannot verify '${GOSU_BINARY##*/}'"
 
-        gpg --batch --verify "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS_SIGNATURE##*/}" \
-            "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}"
+        {
+            gpg --batch --verify "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS_SIGNATURE##*/}" \
+                "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}" &> /dev/null
+        } || die "Cannot verify '${GOSU_SHA256SUMS##*/}'"
 
         local SHA256SUM
         SHA256SUM="$(grep "${GOSU_BINARY##*/}" "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}")"
@@ -51,5 +55,8 @@ downloadGosu ()
         rm -f "${GOSU_DIRECTORY}/${GOSU_BINARY_SIGNATURE##*/}" \
             "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}" \
             "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS_SIGNATURE##*/}"
+
+        mv "${GOSU_DIRECTORY}/${GOSU_BINARY##*/}" "${GOSU_DIRECTORY}/gosu"
+        chmod +x "${GOSU_DIRECTORY}/gosu"
     fi
 }
